# This file was generated by GoReleaser. DO NOT EDIT.
cask "hellbun" do
  name "hellbun"
  desc "A simple Hello, Bun! application"
  homepage "https://github.com/z00b/hello-bun"
  version "0.0.34"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hellbun"

  on_macos do
    on_intel do
      url "https://github.com/z00b/hello-bun/releases/download/v#{version}/hello-bun_Darwin_x86_64.tar.gz"
      sha256 "2ab18bd8af3a9ae8fc3d5fce104062c579f37d19e6db062426e428067f755910"
    end
    on_arm do
      url "https://github.com/z00b/hello-bun/releases/download/v#{version}/hello-bun_Darwin_arm64.tar.gz"
      sha256 "841d1a9ca86984424c7714c9a699217ca14c876e0edd57294de09b970134e384"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/z00b/hello-bun/releases/download/v#{version}/hello-bun_Linux_x86_64.tar.gz"
      sha256 "a8899a9d21c32c228785c67ac8eedb0929ee7ed2746fdc03735712b7295b2382"
    end
    on_arm do
      url "https://github.com/z00b/hello-bun/releases/download/v#{version}/hello-bun_Linux_arm64.tar.gz"
      sha256 "5799ce81e78dbdbcb1ed7f18eaa4f0e839182a6bbebaed771897cc660babfd05"
    end
  end

  # No zap stanza required
end
