# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellbun < Formula
  desc "A simple Hello, Bun! application"
  homepage "https://github.com/z00b/hello-bun"
  version "0.0.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/z00b/hello-bun/releases/download/v0.0.13/hello-bun_Darwin_x86_64.tar.gz"
      sha256 "034d5e67bae96265fc839c5c9e1599f0e1519d448b6a2b97d588b168b8858616"

      def install
        bin.install "hellbun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/z00b/hello-bun/releases/download/v0.0.13/hello-bun_Darwin_arm64.tar.gz"
      sha256 "3a0cdf2636c1d80be765476dd48eee181264f5c62b76f33d5e2ddbc93e84a382"

      def install
        bin.install "hellbun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/z00b/hello-bun/releases/download/v0.0.13/hello-bun_Linux_x86_64.tar.gz"
        sha256 "9debb7d0be9d7fd61fe4dfaa28066faf5c21503f443d023e519c3b695818bac1"

        def install
          bin.install "hellbun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/z00b/hello-bun/releases/download/v0.0.13/hello-bun_Linux_arm64.tar.gz"
        sha256 "dd20208fd675c42109229bd4e741f31c790083a2a4ca1dacc5fd7416810beebc"

        def install
          bin.install "hellbun"
        end
      end
    end
  end

  test do
    system "#{bin}/hellbun"
  end
end
