# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellbun < Formula
  desc "A simple Hello, Bun! application"
  homepage "https://github.com/z00b/hello-bun"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/z00b/hello-bun/releases/download/v0.0.18/hello-bun_Darwin_x86_64.tar.gz"
      sha256 "6c28f06c27aad052da11e2c840e153fe805c7ed9b6f6b7bf9b71bcb155584717"

      def install
        bin.install "hellbun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/z00b/hello-bun/releases/download/v0.0.18/hello-bun_Darwin_arm64.tar.gz"
      sha256 "9b493e2eb447016d79c4896b8ec90cf08986eb5b6343dbaa37dadfa0afaed7b4"

      def install
        bin.install "hellbun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/z00b/hello-bun/releases/download/v0.0.18/hello-bun_Linux_x86_64.tar.gz"
        sha256 "d3a73f7414e02a87578bb01e10a5da0d3ebf820638e3149feba993a33f9ab3db"

        def install
          bin.install "hellbun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/z00b/hello-bun/releases/download/v0.0.18/hello-bun_Linux_arm64.tar.gz"
        sha256 "d3ca3d45742c32a9027bba570e2b0bfc098dfd7ce3b9f02575f6cefb1ffe759c"

        def install
          bin.install "hellbun"
        end
      end
    end
  end

  test do
    system "#{bin}/hellbun"
  end
end
